name: flutter_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # New Dependencies
  flutter_webrtc: ^0.7.0+hotfix.1
  web_socket_channel: 2.1.0
  rxdart: ^0.27.3
  socket_io_client: 2.0.0-beta.4-nullsafety.0
  get: ^4.6.1
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  injectable: ^1.5.3
  shared_preferences: ^2.0.12
  flutter_dotenv: ^5.0.2
  #  flutter_webrtc: ^0.8.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # custom
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  #New Dev Dependencies
  injectable_generator:
  build_runner:
  faker: 2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/env/.env.local
    - assets/env/.env.dev
